export const GET_VPN_SERVER_COUNTRIES_INIT = 'GET_VPN_SERVER_COUNTRIES_INIT';
export const GET_VPN_SERVER_COUNTRIES_SUCCESS = 'GET_VPN_SERVER_COUNTRIES_SUCCESS';
export const GET_VPN_SERVER_COUNTRIES_FAILURE = 'GET_VPN_SERVER_COUNTRIES_FAILURE';

export const CLEAR_VPN_SERVER_COUNTRIES = 'CLEAR_VPN_SERVER_COUNTRIES';
