import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import * as Yup from 'yup'
import classNames from 'classnames'
import friendsVpnLogo from '../public/assets/logos/MainLogo.svg'

import { useFormik } from 'formik'
import { FormFeedback, FormGroup, Input, InputGroup, Label } from 'reactstrap'

export default function Home() {
  const LoginSchema = Yup.object().shape({
    email: Yup.string().email('Please enter a valid email address').required('Email is a required field!'),
    password: Yup.string().required('Password is a required field!')
  })

  const formik = useFormik({
    initialValues: {
      email: '',
      password: ''
    },
    enableReinitialize: true,
    validationSchema: LoginSchema,
    onSubmit: values => {
      if (isObjEmpty(formik.errors)) {
        const { email, password } = values
        const data = {
          email: email.trim(),
          password: password.trim()
        }
        console.log('login data', data)
      }
    }
  })

  return (
    <div className='App'>
      <Head>
        <title>Friends VPN Extension</title>
        <link rel='manifest' href='/manifest.json' />
        <meta name='description' content='Generated by create next app' />
      </Head>

      <div className='Login'>
        <div className='Login__Img_container'>
          <Image src={friendsVpnLogo} alt='Friends VPN' width={163} height={130} />
        </div>
        <div className='Login__formContainer'>
          <form onSubmit={formik.handleSubmit}>
            <FormGroup floating className='form-group'>
              <Input
                autoFocus
                id='Email'
                name='email'
                placeholder='Email'
                type='email'
                {...formik.getFieldProps('email')}
                className={classNames({
                  'is-invalid': formik.touched.email && formik.errors.email
                })}
              />
              <Label for='Email'>Email</Label>
              {formik.touched.email && formik.errors.email ? <FormFeedback>{formik.errors.email}</FormFeedback> : null}
            </FormGroup>
            <FormGroup floating className='form-group'>
              <Input
                id='password'
                name='password'
                placeholder='Password'
                type='password'
                {...formik.getFieldProps('password')}
                className={classNames({
                  'is-invalid': formik.touched.password && formik.errors.password
                })}
              />
              <Label for='password'>password</Label>
              {formik.touched.password && formik.errors.password ? <FormFeedback>{formik.errors.password}</FormFeedback> : null}
            </FormGroup>
          </form>
        </div>

        <div className='Login__text'>
          <p>
            Do not have an account?{' '}
            <Link href='https://www.friendsvpnpro.com/pricing'>
              <a target='_blank'>Register</a>
            </Link>
          </p>
        </div>
      </div>
    </div>
  )
}
