export const USER_LOGGED_IN_INIT = 'USER_LOGGED_IN_INIT'
export const USER_LOGGED_IN_SUCCESS = 'USER_LOGGED_IN_SUCCESS'
export const USER_LOGGED_IN_FAILURE = 'USER_LOGGED_IN_FAILURE'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER'
export const SET_IS_ACCOUNT_TRUE = 'SET_IS_ACCOUNT_TRUE'

export const CLEAR_LOGIN_STATE = 'CLEAR_LOGIN_STATE'
